//
//  string.h
//  KBeacon2
//
//  Created by hogen on 2021/6/8.
//

#ifndef string_h
#define string_h


#define STRING(a) NSLocalizedString(a, a)

#define ACTION_START_SCAN STRING(@"ACTION_START_SCAN")

#define ACTION_STOP_SCAN STRING(@"ACTION_STOP_SCAN")

#define SUCC_TITLE STRING(@"SUCC_TITLE")
#define ERR_TITLE STRING(@"ERR_TITLE")

#define ERR_BEACON_NOT_CONNECTED STRING(@"ERR_BEACON_NOT_CONNECTED")

#define DLG_OK STRING(@"DLG_OK")

#define DLG_CANCEL STRING(@"DLG_CANCEL")

#define ERR_BLE_FUNC_OFF STRING(@"ERR_BLE_FUNC_OFF")

#define ACTION_REFRESHING STRING(@"ACTION_REFRESHING")

#define PUSH_TO_RELEASE STRING(@"PUSH_TO_RELEASE")

#define BEACON_CONNECT STRING(@"BEACON_CONNECT")

#define BEACON_DISCONNECT STRING(@"BEACON_DISCONNECT")



#define DEVICE_CHECK_UPDATE STRING(@"DEVICE_CHECK_UPDATE")

#define DFU_TITLE STRING(@"DFU_TITLE")

#define DEVICE_LATEST_VERSION STRING(@"DEVICE_LATEST_VERSION")

#define DFU_CONNECT_SERVICE_FAIL STRING(@"DFU_CONNECT_SERVICE_FAIL")

#define DFU_FOUND_NEW_VERSION STRING(@"DFU_FOUND_NEW_VERSION")

#define UPDATE_CONNECTING       STRING(@"UPDATE_CONNECTING")

#define UPDATE_UPLOADING       STRING(@"UPDATE_UPLOADING")

#define UPDATE_ABORTED       STRING(@"UPDATE_ABORTED")

#define UPDATE_COMPLETE       STRING(@"UPDATE_COMPLETE")

#define UPDATE_DOWNLOADING STRING(@"UPDATE_DOWNLOADING")

#define UPDATE_NETWORK_FAIL STRING(@"UPDATE_NETWORK_FAIL")

#define UPDATE_STARTED STRING(@"UPDATE_STARTED")


#define DFU_CLOUDS_SERVER_ERROR STRING(@"DFU_CLOUDS_SERVER_ERROR")

#define DFU_CLOUDS_FILE_NOT_EXIST STRING(@"DFU_CLOUDS_FILE_NOT_EXIST")

#define UPDATE_NOT_FOUND_NEW_VERSION STRING(@"UPDATE_NOT_FOUND_NEW_VERSION")

#define DFU_VERSION_MAKE_SURE STRING(@"DFU_VERSION_MAKE_SURE")

#define DEVICE_FOUND_VERSION STRING(@"DEVICE_FOUND_VERSION")

#define EXPORT_SENSOR_HISTORY_DATA_TITLE STRING(@"EXPORT_SENSOR_HISTORY_DATA_TITLE")

#define BEACON_TEMP STRING(@"BEACON_TEMP")
#define BEACON_HUM STRING(@"BEACON_HUM")
#define BEACON_TEMP_UINT STRING(@"BEACON_TEMP_UINT")
#define load_data_complete_no_more_data   STRING(@"load_data_complete_no_more_data")
#define load_data_complete   STRING(@"load_data_complete")

#define nb_clear_history_warning   STRING(@"nb_clear_history_warning")
#define nb_clear_history_description   STRING(@"nb_clear_history_description")

#define LOAD_HISTORY_DATA_FAILED STRING(@"LOAD_HISTORY_DATA_FAILED")
#define LOAD_HISTORY_DATA_TIMEOUT STRING(@"LOAD_HISTORY_DATA_TIMEOUT")
#define upload_data_success STRING(@"upload_data_success")
#define upload_config_data_failed STRING(@"upload_config_data_failed")



#endif /* string_h */
